/* Generated by @deepseek-ai/dsh-typert-generator from FaceModel — do not edit. */
import { z } from 'zod'

const _banbolee_dsh_agents_banboAgentsCatalog_list_result$schema = z.object({
  'agents': z.array(z.object({
  'id': z.string().readonly(),
  'displayName': z.string().readonly(),
  'description': z.string().readonly(),
  'forms': z.array(z.union([z.literal("main"), z.literal("child")])).readonly(),
  'source': z.union([z.literal("built-in"), z.literal("user-file"), z.literal("retired")]).readonly(),
  'retiredReason': z.union([z.undefined(), z.string()]).readonly().optional(),
  'defaultEnabled': z.boolean().readonly(),
  'modelEditable': z.boolean().readonly(),
  'defaultModel': z.union([z.undefined(), z.object({
  'provider': z.string().readonly(),
  'model': z.string().readonly(),
  'reasoningEffort': z.union([z.undefined(), z.string()]).readonly().optional(),
})]).readonly().optional(),
  'allowedChildren': z.array(z.string()).readonly(),
  'toolCapabilities': z.array(z.string()).readonly(),
  'mainBudgetSummary': z.union([z.undefined(), z.record(z.string(), z.number()).readonly()]).readonly().optional(),
})).readonly(),
  'generation': z.string().readonly(),
})

export const TYPERT = {
  package: '@banbolee/dsh-agents',
  face: 'host',
  schemas: [
  ],
  invocations: [
    {
      id: '@banbolee/dsh-agents#banboAgentsCatalog/list',
      service: 'banboAgentsCatalog',
      namespace: 'banboAgentsCatalog',
      method: 'list',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@banbolee/dsh-agents/catalog-remote#AgentCatalogView',
        schema: _banbolee_dsh_agents_banboAgentsCatalog_list_result$schema,
      },
      sourceLocation: {"file":"packages/agents/src/catalog-remote.ts","line":77,"column":9},
    },
  ],
  model: {
    "services": [
      {
        "description": "Remote-only service projecting the startup-static catalog.",
        "summary": "Remote-only service projecting the startup-static catalog.",
        "tags": [
          {
            "name": "typert",
            "comment": "service banboAgentsCatalog",
            "text": "@typert service banboAgentsCatalog"
          }
        ],
        "jsDoc": "/**\n * Remote-only service projecting the startup-static catalog.\n * @typert service banboAgentsCatalog\n */",
        "key": "banboAgentsCatalog",
        "exportName": "BanboAgentsCatalog",
        "members": [
          {
            "kind": "method",
            "name": "list",
            "signature": "@Remote('list') async list(): Promise<AgentCatalogView>"
          }
        ],
        "types": [
          {
            "name": "AgentCatalogRow",
            "declaration": "export interface AgentCatalogRow {\n    readonly id: string;\n    readonly displayName: string;\n    readonly description: string;\n    readonly forms: readonly ('main' | 'child')[];\n    readonly source: 'built-in' | 'user-file' | 'retired';\n    readonly retiredReason?: string;\n    readonly defaultEnabled: boolean;\n    readonly modelEditable: boolean;\n    readonly defaultModel?: AgentModelView;\n    readonly allowedChildren: readonly string[];\n    readonly toolCapabilities: readonly string[];\n    readonly mainBudgetSummary?: Readonly<Record<string, number>>;\n}"
          },
          {
            "name": "AgentCatalogView",
            "declaration": "export interface AgentCatalogView {\n    readonly agents: readonly AgentCatalogRow[];\n    readonly generation: string;\n}"
          },
          {
            "name": "AgentModelView",
            "declaration": "export interface AgentModelView {\n    readonly provider: string;\n    readonly model: string;\n    readonly reasoningEffort?: string;\n}"
          }
        ]
      }
    ],
    "events": [],
    "objects": []
  },
}
