/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { AgentCatalogView } from '@banbolee/dsh-agents/catalog-remote'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$62616e626f4167656e7473436174616c6f67 {
    list: () => Promise<RemoteResult<AgentCatalogView>>
  }
  interface TypertRemoteMap {
    'banboAgentsCatalog/list': () => Promise<RemoteResult<AgentCatalogView>>
  }
  interface TypertRemoteNamespaceMap {
    'banboAgentsCatalog': TypertRemoteNamespace$62616e626f4167656e7473436174616c6f67
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
